# 🔢 1 — NumPy Fundamentals

**Welcome to Week 5: NumPy!** 🎉 NumPy is the **foundation of Data Science and Machine Learning** in Python. Almost every library you'll use later (Pandas, scikit-learn, TensorFlow) is built on top of it. Master this, and the rest becomes much easier.

Every topic is in **simple English**, with **real-life examples** and **line-by-line comments**.

---

## 📚 What you will learn here

| # | Topic |
|---|-------|
| 1 | What is NumPy & why it exists |
| 2 | NumPy vs Python lists |
| 3 | Creating arrays |
| 4 | Array attributes |
| 5 | Changing the data type |
| 6 | Array operations (scalar & vector) |
| 7 | Array functions (max, mean, dot, trig, ...) |
| 8 | Indexing & Slicing (1D, 2D, 3D) |
| 9 | Iterating |
| 10 | Reshaping (transpose, ravel) |
| 11 | Stacking & Splitting |

---

## 1️⃣ What is NumPy?

**NumPy** (Numerical Python) is the fundamental package for **scientific computing** in Python. Its core is the **`ndarray`** object — an **n-dimensional array** that holds items of the **same data type** and lets you do fast maths on large amounts of data.

### 🤔 Why was NumPy created?

Python is loved for its **easy, clean syntax** — but Python's built-in lists are **slow** for heavy number-crunching. So people took the best of both worlds: they wrote a **brand-new data type in the C language** (which is very fast) and plugged it into Python. That's NumPy — **C-level speed with Python-level convenience.** This is exactly why it became the backbone of Data Science and ML. 🚀

## 2️⃣ NumPy vs Python Lists

| Feature | Python list | NumPy array |
|---------|-------------|-------------|
| **Size** | can grow/shrink anytime | fixed at creation (resizing makes a new array) |
| **Data type** | can mix types | all items must be the **same** type |
| **Speed** | slower | **much faster** (written in C) |
| **Maths on whole data** | needs loops | one clean operation on the whole array |
| **Memory** | more | less |

## 3️⃣ Creating NumPy Arrays

First, the standard import. Everyone imports NumPy as **`np`**.

In [ ]:
import numpy as np

### `np.array()` — from a Python list
- **1D array** = a **vector**
- **2D array** = a **matrix** (rows & columns)
- **3D array** = a **tensor**

In [ ]:
# 1D array (vector)
a = np.array([1, 2, 3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
# 2D array (matrix) — a list of lists
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3D array (tensor) — a list of matrices
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Choosing the data type with `dtype`
By default items are integers, but you can request `float`, `bool`, `complex`, etc.

In [ ]:
np.array([1, 2, 3, 4], dtype=float)   # force a float array

array([1., 2., 3., 4.])

In [ ]:
np.array([1, 2, 3], dtype=bool)   # any non-zero number becomes True

array([ True,  True,  True])

In [ ]:
np.array([1, 2, 3], dtype=complex)   # complex numbers

array([1.+0.j, 2.+0.j, 3.+0.j])

### `np.arange()` — like Python's `range()`
Creates an array of evenly spaced numbers.

In [ ]:
np.arange(1, 11)   # 1 to 10

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1, 11, 2)   # step of 2

array([1, 3, 5, 7, 9])

### `reshape()` — change the shape
Turn a 1D array into a matrix. **The numbers must multiply to the total item count** (e.g. 10 items → 5×2 ✓, but not 5×5 ✗).

In [ ]:
np.arange(1, 11).reshape(5, 2)   # 5 rows, 2 columns

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
np.arange(1, 13).reshape(3, 4)   # 12 items -> 3 rows, 4 columns

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

⚠️ You **can't** reshape into a shape that doesn't match the item count. 10 items into 5×5 (which needs 25) gives an error. *(Fixed from the original, which showed a `.rehsape` spelling-typo error instead of the real shape error.)*

In [ ]:
np.arange(1, 11).reshape(5, 5)   # ❌ ValueError: cannot reshape array of size 10 into shape (5,5)

### Quick-fill arrays: `ones`, `zeros`, `random`, `linspace`, `identity`
These create arrays instantly without typing every value (pass the **shape as a tuple**).

In [ ]:
np.ones((3, 4))   # a 3x4 array full of 1s — handy for quick initialization

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3, 4))   # a 3x4 array full of 0s

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.random.random((3, 4))   # random numbers between 0 and 1 (your numbers will differ)

array([[0.14314444, 0.79838156, 0.20249747, 0.0447336 ],
       [0.16668362, 0.62079961, 0.62781972, 0.54366873],
       [0.43915386, 0.80962184, 0.48268609, 0.97315907]])

In [ ]:
np.linspace(-10, 10, 10)   # 10 evenly-spaced points from -10 to 10

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
np.identity(3)   # a 3x3 identity matrix (1s on the diagonal, 0s elsewhere)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 4️⃣ Array Attributes

Every array carries information about itself. Let's make three arrays and inspect them.

In [ ]:
a1 = np.arange(10)                        # 1D vector
a2 = np.arange(12, dtype=float).reshape(3, 4)  # 2D matrix
a3 = np.arange(8).reshape(2, 2, 2)        # 3D tensor

| Attribute | Meaning |
|-----------|---------|
| `ndim` | number of dimensions (1D, 2D, 3D...) |
| `shape` | items in each dimension, e.g. `(rows, cols)` |
| `size` | total number of items |
| `itemsize` | bytes used by **one** item |
| `dtype` | the data type of the items |

In [ ]:
print(a1.ndim)   # 1
print(a2.ndim)   # 2
print(a3.ndim)   # 3

1
2
3


In [ ]:
print(a1.shape)   # (10,)  -> 10 items
print(a2.shape)   # (3, 4)  -> 3 rows, 4 columns
print(a3.shape)   # (2, 2, 2) -> two 2x2 matrices

(10,)
(3, 4)
(2, 2, 2)


In [ ]:
print(a2.size)   # 12 total items
print(a3.size)   # 8 total items

12
8


In [ ]:
print(a1.itemsize)   # bytes per item (int64 -> 8 bytes)
print(a1.dtype, a2.dtype, a3.dtype)

8
int64 float64 int64


> 💡 A 64-bit integer (`int64`) takes **8 bytes**; a 32-bit integer (`int32`) takes only **4 bytes**. Choosing a smaller type saves memory.

In [ ]:
b1 = np.arange(10, dtype=np.int32)
b1.itemsize   # 4 bytes (int32)

4

## 5️⃣ Changing the Data Type — `astype()`

You can convert an existing array to a smaller/different type to **save memory**. For example, if an array only stores people's **ages**, you don't need a huge `int64` — `int32` (or even smaller) is plenty.

In [ ]:
a3 = np.arange(8).reshape(2, 2, 2)
a3.astype(np.int32)   # convert int64 -> int32 (uses less memory)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

## 6️⃣ Array Operations

You can run maths on whole arrays at once — no loops needed! There are two kinds:
- **Scalar operations** — array **with a single number**.
- **Vector operations** — array **with another array**.

In [ ]:
a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(12, 24).reshape(3, 4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


### Scalar operations — every item reacts to the single number

In [ ]:
print(a1 * 2)   # multiply every item by 2

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [ ]:
a1 > 5   # relational — asks each item "are you greater than 5?" -> True/False

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

### Vector operations — two arrays of the **same shape** combine item-by-item

In [ ]:
a1 + a2   # add matching positions

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [ ]:
a1 * a2   # multiply matching positions (element-wise, NOT matrix multiplication)

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

## 7️⃣ Array Functions

NumPy has hundreds of built-in maths functions. Let's make a random matrix to try them on.

In [ ]:
a1 = np.round(np.random.random((3, 3)) * 100)   # random whole numbers 0-100 (yours will differ)
a1

array([[ 24.,  43.,  21.],
       [100.,  17.,  78.],
       [ 68.,  27.,  92.]])

### max / min / sum / prod

In [ ]:
print(np.max(a1))   # biggest value
print(np.min(a1))   # smallest value
print(np.sum(a1))   # total
print(np.prod(a1))  # product of all

100.0
17.0
470.0
485403630566400.0


### The `axis` argument — row-wise vs column-wise ⭐

This is a very common source of confusion:
- **`axis=0`** works **down the columns** (gives one result per column).
- **`axis=1`** works **across the rows** (gives one result per row).

In [ ]:
print(np.max(a1, axis=1))   # max of each ROW
print(np.max(a1, axis=0))   # max of each COLUMN

[ 43. 100.  92.]
[100.  43.  92.]


### Statistics: mean / median / std / var

In [ ]:
print(np.mean(a1))     # average
print(np.median(a1))   # middle value
print(np.std(a1))      # standard deviation
print(np.var(a1))      # variance

52.22222222222222
43.0
30.752697362373407
945.7283950617283


### Other useful functions
- **Trigonometry:** `np.sin`, `np.cos`
- **Logs & exponents:** `np.log`, `np.exp`
- **Rounding:** `np.round`, `np.floor`, `np.ceil`

In [ ]:
np.round(np.random.random((2, 3)) * 100)   # round to nearest whole number

array([[61., 90.,  8.],
       [72., 26., 42.]])

### Dot product (matrix multiplication) — `np.dot`
For `np.dot(A, B)`, the **columns of A must equal the rows of B**. If A is `(3,4)` and B is `(4,3)`, the result is `(3,3)`.

In [ ]:
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(12, 24).reshape(4, 3)
np.dot(a2, a3)   # (3,4) . (4,3) -> (3,3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

## 8️⃣ Indexing — Fetching a Single Item

Indexing grabs **one** item. The rule for multi-dimensional arrays: give the position in **each** dimension, separated by commas.

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)

### 1D — just the position

In [ ]:
print(a1[0])    # first item -> 0
print(a1[-1])   # last item -> 9

0
9


### 2D — `array[row, column]` (counting starts at 0)

In [ ]:
# a2 = [[0,1,2,3],[4,5,6,7],[8,9,10,11]]
print(a2[1, 2])   # row 1, column 2 -> 6
print(a2[2, 3])   # row 2, column 3 -> 11
print(a2[1, 0])   # row 1, column 0 -> 4

6
11
4


### 3D — `array[matrix, row, column]`
A 3D array is made of 2D arrays. First pick which 2D matrix, then the row and column inside it.

In [ ]:
# a3 = [[[0,1],[2,3]], [[4,5],[6,7]]]
print(a3[1, 0, 1])   # 2nd matrix, row 0, col 1 -> 5
print(a3[0, 1, 0])   # 1st matrix, row 1, col 0 -> 2
print(a3[1, 1, 0])   # 2nd matrix, row 1, col 0 -> 6

5
2
6


## 9️⃣ Slicing — Fetching Multiple Items

Slicing uses `start:stop:step`, just like Python lists — but you can slice **each dimension** separately.

**Key idea for 2D:** `array[rows, columns]`. Use `:` to mean "all of this dimension."
- `a2[0, :]` → the whole first **row**.
- `a2[:, 2]` → the whole third **column**.

In [ ]:
a2 = np.arange(12).reshape(3, 4)
print(a2[0, :])   # first row
print(a2[:, 2])   # third column

[0 1 2 3]
[ 2  6 10]


In [ ]:
# a sub-block: rows from index 1, columns 1 to 2
a2[1:, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
# with steps: every 2nd row, every 3rd column
a2[::2, ::3]

array([[ 0,  3],
       [ 8, 11]])

### Slicing 3D — pick matrices, then rows/columns

In [ ]:
a3 = np.arange(27).reshape(3, 3, 3)   # three 3x3 matrices
a3[1]   # the whole middle (2nd) matrix

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
a3[0, 1, :]   # 1st matrix, 2nd row, all columns

array([3, 4, 5])

In [ ]:
a3[1, :, 1]   # 2nd matrix, all rows, middle column

array([10, 13, 16])

## 🔟 Iterating

Looping over an array gives you one "slice" per dimension:
- Over a **1D** array → each item.
- Over a **2D** array → each **row**.
- Over a **3D** array → each **2D matrix**.

In [ ]:
a2 = np.arange(12).reshape(3, 4)
for row in a2:
    print(row)   # each iteration gives a whole row

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


### `np.nditer` — loop over **every single item**
No matter how many dimensions, `np.nditer` flattens it and gives you one item at a time.

In [ ]:
a3 = np.arange(8).reshape(2, 2, 2)
for item in np.nditer(a3):
    print(item, end=" ")

0 1 2 3 4 5 6 7 

## 1️⃣1️⃣ Reshaping

Three handy ways to change an array's shape:
| Function | What it does |
|----------|--------------|
| `reshape` | change to any matching shape (we saw this earlier) |
| `transpose` (or `.T`) | flip rows ↔ columns |
| `ravel` | flatten any array down to 1D |

In [ ]:
a2 = np.arange(12).reshape(3, 4)
np.transpose(a2)   # or a2.T — rows become columns

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
a2.ravel()   # flatten a 2D array into 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## 1️⃣2️⃣ Stacking — Joining Arrays

You can join two or more arrays together. **Condition:** their shapes must match along the joining side.
- **`hstack`** → join **horizontally** (side by side).
- **`vstack`** → join **vertically** (top and bottom).

🧠 **Real use:** in Data Science, data often comes from many sources (a database, an API, web scraping). Stacking lets you combine them into one array for analysis.

In [ ]:
a4 = np.arange(12).reshape(3, 4)
a5 = np.arange(12, 24).reshape(3, 4)

np.hstack((a4, a5))   # side by side

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
np.vstack((a4, a5))   # stacked top and bottom

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## 1️⃣3️⃣ Splitting — the Opposite of Stacking

Break one array into several equal parts.
- **`hsplit`** → split into columns.
- **`vsplit`** → split into rows.

🧠 **Real use:** you have a college's data and want to split it branch-wise.

In [ ]:
a4 = np.arange(12).reshape(3, 4)
np.hsplit(a4, 2)   # split into 2 equal column-halves

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
a5 = np.arange(12, 24).reshape(3, 4)
np.vsplit(a5, 3)   # split into 3 equal rows

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

---

## 🎯 Summary — Quick Revision

You've learned the foundation of Data Science in Python! 🎉

| Topic | Key idea |
|-------|----------|
| **NumPy** | Fast C-powered arrays (`ndarray`); same-type items |
| **Creating** | `array`, `arange`, `ones`, `zeros`, `random`, `linspace`, `identity` |
| **Attributes** | `ndim`, `shape`, `size`, `itemsize`, `dtype` |
| **`astype`** | Convert type to save memory |
| **Operations** | Scalar (array + number) & vector (array + array), element-wise |
| **Functions** | `max/min/sum/mean/std`; `axis=0` (columns), `axis=1` (rows) |
| **`np.dot`** | Matrix multiplication (inner dimensions must match) |
| **Indexing** | `[row, col]` for 2D; `[matrix, row, col]` for 3D |
| **Slicing** | `start:stop:step` per dimension; `:` means "all" |
| **Reshaping** | `reshape`, `transpose`/`.T`, `ravel` |
| **Stacking/Splitting** | `hstack`/`vstack`, `hsplit`/`vsplit` |

---

### 📝 Try It Yourself (Practice Questions)

1. Create a 3×3 array of random numbers between 0 and 1, and find its mean.
2. Make a `np.arange(1, 26)` and reshape it into a 5×5 matrix.
3. From a 4×4 matrix, extract the middle 2×2 block using slicing.
4. Find the maximum of each column of a 3×4 array (use `axis`).
5. Stack two 2×3 arrays vertically, then split the result back into 2 parts.

> 💪 **Remember:** NumPy is used in *every* Data Science project. Play with shapes, slicing, and `axis` until they feel natural — it will pay off in Pandas and Machine Learning!

---

**➡️ Next up: 2 — Advanced NumPy.**